In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import import_ipynb
from EDA import strong_corr_df
df = pd.read_csv('AmesHousing.csv')

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

# Handling missing values

In [50]:
null_counts = df.isnull().sum()

threshold = len(df) * 0.1

columns_with_nulls = null_counts[null_counts > threshold].index.tolist()

columns_with_nulls

['Lot Frontage',
 'Alley',
 'Mas Vnr Type',
 'Fireplace Qu',
 'Pool QC',
 'Fence',
 'Misc Feature']

In [51]:
df_new = df.drop(columns_with_nulls, axis=1)

df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 75 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Area         2930 non-null   int64
 5   Street           2930 non-null   object
 6   Lot Shape        2930 non-null   object
 7   Land Contour     2930 non-null   object
 8   Utilities        2930 non-null   object
 9   Lot Config       2930 non-null   object
 10  Land Slope       2930 non-null   object
 11  Neighborhood     2930 non-null   object
 12  Condition 1      2930 non-null   object
 13  Condition 2      2930 non-null   object
 14  Bldg Type        2930 non-null   object
 15  House Style      2930 non-null   object
 16  Overall Qual     2930 non-null   int64
 17  Overall Cond     2930 non-null   int64
 18  Year Built       2930 non-null   int64
 19  Year Remod/Add   2930 non-null   int64
 20  Roof Style       2930 non-null   object
 21  Roof Matl        2930 non-null   object
 22  Exterior 1st     2930 non-null   object
 23  Exterior 2nd     2930 non-null   object
 24  Mas Vnr Area     2907 non-null   float64
 25  Exter Qual       2930 non-null   object
 26  Exter Cond       2930 non-null   object
 27  Foundation       2930 non-null   object
 28  Bsmt Qual        2850 non-null   object
 29  Bsmt Cond        2850 non-null   object
 30  Bsmt Exposure    2847 non-null   object
 31  BsmtFin Type 1   2850 non-null   object
 32  BsmtFin SF 1     2929 non-null   float64
 33  BsmtFin Type 2   2849 non-null   object
 34  BsmtFin SF 2     2929 non-null   float64
 35  Bsmt Unf SF      2929 non-null   float64
 36  Total Bsmt SF    2929 non-null   float64
 37  Heating          2930 non-null   object
 38  Heating QC       2930 non-null   object
 39  Central Air      2930 non-null   object
 40  Electrical       2929 non-null   object
 41  1st Flr SF       2930 non-null   int64
 42  2nd Flr SF       2930 non-null   int64
 43  Low Qual Fin SF  2930 non-null   int64
 44  Gr Liv Area      2930 non-null   int64
 45  Bsmt Full Bath   2928 non-null   float64
 46  Bsmt Half Bath   2928 non-null   float64
 47  Full Bath        2930 non-null   int64
 48  Half Bath        2930 non-null   int64
 49  Bedroom AbvGr    2930 non-null   int64
 50  Kitchen AbvGr    2930 non-null   int64
 51  Kitchen Qual     2930 non-null   object
 52  TotRms AbvGrd    2930 non-null   int64
 53  Functional       2930 non-null   object
 54  Fireplaces       2930 non-null   int64
 55  Garage Type      2773 non-null   object
 56  Garage Yr Blt    2771 non-null   float64
 57  Garage Finish    2771 non-null   object
 58  Garage Cars      2929 non-null   float64
 59  Garage Area      2929 non-null   float64
 60  Garage Qual      2771 non-null   object
 61  Garage Cond      2771 non-null   object
 62  Paved Drive      2930 non-null   object
 63  Wood Deck SF     2930 non-null   int64
 64  Open Porch SF    2930 non-null   int64
 65  Enclosed Porch   2930 non-null   int64
 66  3Ssn Porch       2930 non-null   int64
 67  Screen Porch     2930 non-null   int64
 68  Pool Area        2930 non-null   int64
 69  Misc Val         2930 non-null   int64
 70  Mo Sold          2930 non-null   int64
 71  Yr Sold          2930 non-null   int64
 72  Sale Type        2930 non-null   object
 73  Sale Condition   2930 non-null   object
 74  SalePrice        2930 non-null   int64
dtypes: float64(10), int64(28), object(37)
memory usage: 1.7+ MB

In [52]:
missing_value_columns = df_new.columns[df_new.isnull().any()]

print(missing_value_columns)

numeric_columns_with_missing_values = df_new[missing_value_columns].select_dtypes(include=[np.number]).columns.tolist()

numeric_columns_with_missing_values

for col in missing_value_columns:
    if df_new[col].dtype == 'object':
        df_new[col] = df_new[col].fillna('None')
    else:
        df_new[col] = df_new[col].fillna(df_new[col].median())

df_new.info()

Index(['Mas Vnr Area', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Electrical', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Garage Type', 'Garage Yr Blt', 'Garage Finish',
       'Garage Cars', 'Garage Area', 'Garage Qual', 'Garage Cond'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 75 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Area         2930 non-null   int64
 5   Street           2930 non-null   object
 6   Lot Shape        2930 non-null   object
 7   Land Contour     2930 non-null   object
 8   Utilities        2930 non-null   object
 9   Lot Config       2930 non-null   object
 10  Land Slope       2930 non-null   object
 11  Neighborhood     2930 non-null   object
 12  Condition 1      2930 non-null   object
 13  Condition 2      2930 non-null   object
 14  Bldg Type        2930 non-null   object
 15  House Style      2930 non-null   object
 16  Overall Qual     2930 non-null   int64
 17  Overall Cond     2930 non-null   int64
 18  Year Built       2930 non-null   int64
 19  Year Remod/Add   2930 non-null   int64
 20  Roof Style       2930 non-null   object
 21  Roof Matl        2930 non-null   object
 22  Exterior 1st     2930 non-null   object
 23  Exterior 2nd     2930 non-null   object
 24  Mas Vnr Area     2930 non-null   float64
 25  Exter Qual       2930 non-null   object
 26  Exter Cond       2930 non-null   object
 27  Foundation       2930 non-null   object
 28  Bsmt Qual        2930 non-null   object
 29  Bsmt Cond        2930 non-null   object
 30  Bsmt Exposure    2930 non-null   object
 31  BsmtFin Type 1   2930 non-null   object
 32  BsmtFin SF 1     2930 non-null   float64
 33  BsmtFin Type 2   2930 non-null   object
 34  BsmtFin SF 2     2930 non-null   float64
 35  Bsmt Unf SF      2930 non-null   float64
 36  Total Bsmt SF    2930 non-null   float64
 37  Heating          2930 non-null   object
 38  Heating QC       2930 non-null   object
 39  Central Air      2930 non-null   object
 40  Electrical       2930 non-null   object
 41  1st Flr SF       2930 non-null   int64
 42  2nd Flr SF       2930 non-null   int64
 43  Low Qual Fin SF  2930 non-null   int64
 44  Gr Liv Area      2930 non-null   int64
 45  Bsmt Full Bath   2930 non-null   float64
 46  Bsmt Half Bath   2930 non-null   float64
 47  Full Bath        2930 non-null   int64
 48  Half Bath        2930 non-null   int64
 49  Bedroom AbvGr    2930 non-null   int64
 50  Kitchen AbvGr    2930 non-null   int64
 51  Kitchen Qual     2930 non-null   object
 52  TotRms AbvGrd    2930 non-null   int64
 53  Functional       2930 non-null   object
 54  Fireplaces       2930 non-null   int64
 55  Garage Type      2930 non-null   object
 56  Garage Yr Blt    2930 non-null   float64
 57  Garage Finish    2930 non-null   object
 58  Garage Cars      2930 non-null   float64
 59  Garage Area      2930 non-null   float64
 60  Garage Qual      2930 non-null   object
 61  Garage Cond      2930 non-null   object
 62  Paved Drive      2930 non-null   object
 63  Wood Deck SF     2930 non-null   int64
 64  Open Porch SF    2930 non-null   int64
 65  Enclosed Porch   2930 non-null   int64
 66  3Ssn Porch       2930 non-null   int64
 67  Screen Porch     2930 non-null   int64
 68  Pool Area        2930 non-null   int64
 69  Misc Val         2930 non-null   int64
 70  Mo Sold          2930 non-null   int64
 71  Yr Sold          2930 non-null   int64
 72  Sale Type        2930 non-null   object
 73  Sale Condition   2930 non-null   object
 74  SalePrice        2930 non-null   int64
dtypes: float64(10), int64(28), object(37)
memory usage: 1.7+ MB

In [53]:
empty_columns = df_new.isnull().values.all()

empty_columns

False

# Checking for duplicates

In [54]:
duplicates = df.duplicated().sum()

duplicates

0

# Checking if all the values are in the correct format

In [55]:
df_numeric = df_new.select_dtypes(include=[np.number])

df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   Lot Area         2930 non-null   int64
 4   Overall Qual     2930 non-null   int64
 5   Overall Cond     2930 non-null   int64
 6   Year Built       2930 non-null   int64
 7   Year Remod/Add   2930 non-null   int64
 8   Mas Vnr Area     2930 non-null   float64
 9   BsmtFin SF 1     2930 non-null   float64
 10  BsmtFin SF 2     2930 non-null   float64
 11  Bsmt Unf SF      2930 non-null   float64
 12  Total Bsmt SF    2930 non-null   float64
 13  1st Flr SF       2930 non-null   int64
 14  2nd Flr SF       2930 non-null   int64
 15  Low Qual Fin SF  2930 non-null   int64
 16  Gr Liv Area      2930 non-null   int64
 17  Bsmt Full Bath   2930 non-null   float64
 18  Bsmt Half Bath   2930 non-null   float64
 19  Full Bath        2930 non-null   int64
 20  Half Bath        2930 non-null   int64
 21  Bedroom AbvGr    2930 non-null   int64
 22  Kitchen AbvGr    2930 non-null   int64
 23  TotRms AbvGrd    2930 non-null   int64
 24  Fireplaces       2930 non-null   int64
 25  Garage Yr Blt    2930 non-null   float64
 26  Garage Cars      2930 non-null   float64
 27  Garage Area      2930 non-null   float64
 28  Wood Deck SF     2930 non-null   int64
 29  Open Porch SF    2930 non-null   int64
 30  Enclosed Porch   2930 non-null   int64
 31  3Ssn Porch       2930 non-null   int64
 32  Screen Porch     2930 non-null   int64
 33  Pool Area        2930 non-null   int64
 34  Misc Val         2930 non-null   int64
 35  Mo Sold          2930 non-null   int64
 36  Yr Sold          2930 non-null   int64
 37  SalePrice        2930 non-null   int64
dtypes: float64(10), int64(28)
memory usage: 870.0 KB

# Handling outliers

In [56]:
Q1 = df_numeric.quantile(0.25)
Q3 = df_numeric.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR

upper_bound = Q3 + 1.5 * IQR

outliers = (df_numeric < (lower_bound)) | (df_numeric > (upper_bound))

print(outliers.any())

outliers.sum()

Order              False
PID                False
MS SubClass         True
Lot Area            True
Overall Qual        True
Overall Cond        True
Year Built          True
Year Remod/Add     False
Mas Vnr Area        True
BsmtFin SF 1        True
BsmtFin SF 2        True
Bsmt Unf SF         True
Total Bsmt SF       True
1st Flr SF          True
2nd Flr SF          True
Low Qual Fin SF     True
Gr Liv Area         True
Bsmt Full Bath      True
Bsmt Half Bath      True
Full Bath           True
Half Bath          False
Bedroom AbvGr       True
Kitchen AbvGr       True
TotRms AbvGrd       True
Fireplaces          True
Garage Yr Blt       True
Garage Cars         True
Garage Area         True
Wood Deck SF        True
Open Porch SF       True
Enclosed Porch      True
3Ssn Porch          True
Screen Porch        True
Pool Area           True
Misc Val            True
Mo Sold            False
Yr Sold            False
SalePrice           True
dtype: bool

Order                0
PID                  0
MS SubClass        208
Lot Area           127
Overall Qual         4
Overall Cond       252
Year Built           9
Year Remod/Add       0
Mas Vnr Area       203
BsmtFin SF 1        15
BsmtFin SF 2       351
Bsmt Unf SF         56
Total Bsmt SF      123
1st Flr SF          43
2nd Flr SF           8
Low Qual Fin SF     40
Gr Liv Area         75
Bsmt Full Bath       2
Bsmt Half Bath     175
Full Bath            4
Half Bath            0
Bedroom AbvGr       78
Kitchen AbvGr      134
TotRms AbvGrd       51
Fireplaces          13
Garage Yr Blt        9
Garage Cars         17
Garage Area         42
Wood Deck SF        67
Open Porch SF      159
Enclosed Porch     459
3Ssn Porch          37
Screen Porch       256
Pool Area           13
Misc Val           103
Mo Sold              0
Yr Sold              0
SalePrice          137
dtype: int64

In [57]:
for column in df_numeric.columns:
    
    median = df_numeric[column].median()
    
    df_numeric[column] = np.where(df_numeric[column] < lower_bound[column], median, df_numeric[column])

    df_numeric[column] = np.where(df_numeric[column] > upper_bound[column], median, df_numeric[column])

df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   float64
 1   PID              2930 non-null   float64
 2   MS SubClass      2930 non-null   float64
 3   Lot Area         2930 non-null   float64
 4   Overall Qual     2930 non-null   float64
 5   Overall Cond     2930 non-null   float64
 6   Year Built       2930 non-null   float64
 7   Year Remod/Add   2930 non-null   float64
 8   Mas Vnr Area     2930 non-null   float64
 9   BsmtFin SF 1     2930 non-null   float64
 10  BsmtFin SF 2     2930 non-null   float64
 11  Bsmt Unf SF      2930 non-null   float64
 12  Total Bsmt SF    2930 non-null   float64
 13  1st Flr SF       2930 non-null   float64
 14  2nd Flr SF       2930 non-null   float64
 15  Low Qual Fin SF  2930 non-null   float64
 16  Gr Liv Area      2930 non-null   float64
 17  Bsmt Full Bath   2930 non-null   float64
 18  Bsmt Half Bath   2930 non-null   float64
 19  Full Bath        2930 non-null   float64
 20  Half Bath        2930 non-null   float64
 21  Bedroom AbvGr    2930 non-null   float64
 22  Kitchen AbvGr    2930 non-null   float64
 23  TotRms AbvGrd    2930 non-null   float64
 24  Fireplaces       2930 non-null   float64
 25  Garage Yr Blt    2930 non-null   float64
 26  Garage Cars      2930 non-null   float64
 27  Garage Area      2930 non-null   float64
 28  Wood Deck SF     2930 non-null   float64
 29  Open Porch SF    2930 non-null   float64
 30  Enclosed Porch   2930 non-null   float64
 31  3Ssn Porch       2930 non-null   float64
 32  Screen Porch     2930 non-null   float64
 33  Pool Area        2930 non-null   float64
 34  Misc Val         2930 non-null   float64
 35  Mo Sold          2930 non-null   float64
 36  Yr Sold          2930 non-null   float64
 37  SalePrice        2930 non-null   float64
dtypes: float64(38)
memory usage: 870.0 KB

# Normalizing data

In [58]:
from sklearn.preprocessing import MinMaxScaler

In [60]:
df_numeric = pd.DataFrame(df_numeric, columns=df_new.select_dtypes(include=[np.number]).columns)

df_new[df_numeric.columns] = df_numeric

df_filtered = df_new

df_new

,Order,PID,MS SubClass,MS Zoning,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1.0,526301100.0,20.0,RL,9436.5,Pave,IR1,Lvl,AllPub,Corner,...,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,WD,Normal,215000.0
1,2.0,526350040.0,20.0,RH,11622.0,Pave,Reg,Lvl,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,WD,Normal,105000.0
2,3.0,526351010.0,20.0,RL,14267.0,Pave,IR1,Lvl,AllPub,Corner,...,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,WD,Normal,172000.0
3,4.0,526353030.0,20.0,RL,11160.0,Pave,Reg,Lvl,AllPub,Corner,...,0.0,0.0,0.0,0.0,0.0,4.0,2010.0,WD,Normal,244000.0
4,5.0,527105010.0,60.0,RL,13830.0,Pave,IR1,Lvl,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,WD,Normal,189900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926.0,923275080.0,80.0,RL,7937.0,Pave,IR1,Lvl,AllPub,CulDSac,...,0.0,0.0,0.0,0.0,0.0,3.0,2006.0,WD,Normal,142500.0
2926,2927.0,923276100.0,20.0,RL,8885.0,Pave,IR1,Low,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,WD,Normal,131000.0
2927,2928.0,923400125.0,85.0,RL,10441.0,Pave,Reg,Lvl,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,WD,Normal,132000.0
2928,2929.0,924100070.0,20.0,RL,10010.0,Pave,Reg,Lvl,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,4.0,2006.0,WD,Normal,170000.0
2929,2930.0,924151050.0,60.0,RL,9627.0,Pave,Reg,Lvl,AllPub,Inside,...,0.0,0.0,0.0,0.0,0.0,11.0,2006.0,WD,Normal,188000.0

In [61]:
correlated_variables = strong_corr_df['Variables']  

correlated_variables = pd.concat([correlated_variables, pd.Series(['SalePrice'])]).reset_index(drop=True)

correlated_variables

0        Gr Liv Area
1        Garage Cars
2        Garage Area
3      Total Bsmt SF
4         1st Flr SF
5         Year Built
6          Full Bath
7     Year Remod/Add
8      Garage Yr Blt
9       Mas Vnr Area
10         SalePrice
dtype: object

In [71]:
Final_df = df_filtered[correlated_variables]

Final_df

scaler = MinMaxScaler()

scaler.fit(Final_df)

df_normalized = scaler.transform(Final_df)

df_normalized = pd.DataFrame(df_normalized, columns=Final_df.columns)

df_normalized.to_csv('AmesHousingNormalized.csv', index=False)